import "./globals.css";
export const metadata = {
  title: 'Vehicle Registration System',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="auto-grab">
      <body>{children}</body>
    </html>
  )
}
